/api/v1/role/get:
  get:
    tags:
      - Role
    security:
    - bearerAuth: []
    description: Listar roles
    produces:
      - application/json
    responses:
      200:
        description: Petición exitosa
        content:
          applicaiton/json:
            schema:
              type: array
            example:
              {
                "state": true,
                "message": "Listado de roles",
                "roles": [
                  {
                    "id": 2,
                    "name": "Estudiante",
                    "state": true,
                    "created_at": "2023-03-20T16:03:34.628-05:00",
                    "updated_at": "2023-03-20T16:03:34.628-05:00"
                  },
                  {
                    "id": 1,
                    "name": "Administrador",
                    "state": true,
                    "created_at": "2023-03-20T16:03:28.896-05:00",
                    "updated_at": "2023-03-20T16:03:28.924-05:00"
                  }
                ]
              }